import ReactSlider from '../../../components/Slider/slider';
import Speaker from '../../../components/Speaker/speaker';
import Sponsors from '../../../components/Sponsors/sponsors';
import Heading from '../../../components/Typography/heading';
import Paragraph from '../../../components/Typography/paragraph';
import cities from '../../../config/city-lists.json';
import speakers from '../../../config/speakers.json';
import Venue from '../../../components/Venue/venue';
import Head from 'next/head';
import About from '../../../components/About/about';
import { CommonUtils } from '../../../utils/common-utils';
import Button from '../../../components/Buttons/button';


export async function getStaticProps({ params }) {
    let res = [];
    let yearEvents = [];
    const data = cities.filter((p) => CommonUtils.extractYear(p.date) === params.year);
    yearEvents = data;
    for (let i = 0; i < yearEvents.length; i++) {
        let yearIter = yearEvents[i];
        const getSpeakers = speakers.filter((s) => s.city === yearIter?.name && s.year === CommonUtils.extractYear(yearIter.date));
        yearIter.speakers = getSpeakers[0].lists;
        res.push(yearIter);
    }
    return {
        props: {
            year: params.year,
            data: res,
        },
    };
}

export async function getStaticPaths() {
    const paths = cities.map((city) => ({
        params: { year: CommonUtils.extractYear(city.date) },
    }));
    return {
        paths,
        fallback: false,
    };
}

const Edition = (props) => {

    const year = props.year;
    const speakers = props.data.map(item => item.speakers)
    const cities = props.data

    return <div>
        <Head>
            <title>AsyncAPI Conference {year}</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
        <div id='about'>
            <About year={year} isEnded={true} />
        </div>
        <div className='gradient-bg py-10 w-full container flex flex-col justify-center items-center'>
            <div className='w-[1130px] lg:w-full flex lg:py-20 flex-col items-center justify-center'>
                <div className='text-center py-[46px] w-[714px] lg:w-full'>
                    <Heading className='text-white'>Venues</Heading>
                    <Paragraph className='mt-12'>
                        The AsyncAPI Conf on Tour {year} took the online
                        event to the next level by hosting physical events in {cities.length} {" "}
                        different locations across the globe.
                    </Paragraph>
                </div>
                <div className='w-full mt-[64px]'>
                    <ReactSlider>
                        {cities.map((_city) => {
                            return <Venue key={_city.name} city={_city} />;
                        })}
                    </ReactSlider>
                </div>
            </div>
        </div>
        <div
            id='speakers'
            className='pt-[160px] container relative flex flex-col items-center justify-center'
        >
            <div className='lg:py-20 w-[1130px] lg:w-full'>
                <div className='text-center'>
                    <Heading className='text-white'>Speakers</Heading>
                    <Paragraph className='mt-[20px] text-white'>Meet the speakers</Paragraph>
                </div>

                <div className='my-10'>
                    <div className='w-full mt-[64px]'>
                        <ReactSlider isAutoPlay={true}>
                            {speakers.flat().map((speaker, i) => {
                                return (
                                    <Speaker
                                        key={i}
                                        details={speaker}
                                        location={'India'}
                                        className='mt-10 mx-5 max-w-[500px]'
                                    />
                                );
                            })}
                        </ReactSlider>

                        <div className='flex items-center justify-center'>
                           <a href={`/editions/${year}/speakers`}>
                             <Button className='w-[200px] mx-auto'>
                                View all speakers
                            </Button>
                           </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id='sponsors'>
            <Sponsors imgs={['/img/sngular.png', '/img/IBM.png', '/img/postman.png', '/img/apidays.png']} />
        </div>
    </div>
}

export default Edition;