import ReactSlider from '../../../components/Slider/slider';
import Speaker from '../../../components/Speaker/speaker';
import Sponsors from '../../../components/Sponsors/sponsors';
import Heading from '../../../components/Typography/heading';
import Paragraph from '../../../components/Typography/paragraph';
import cities from '../../../config/city-lists.json';
import speakers from '../../../config/speakers.json';
import Venue from '../../../components/Venue/venue';
import Head from 'next/head';
import About from '../../../components/About/about';
import { CommonUtils } from '../../../utils/common-utils';


export async function getStaticProps({ params }) {
    let res = [];
    let yearEvents = [];
    const data = cities.filter((p) => CommonUtils.extractYear(p.date) === params.year);
    yearEvents = data;
    for (let i = 0; i < yearEvents.length; i++) {
        let yearIter = yearEvents[i];
        const getSpeakers = speakers.filter((s) => s.city === yearIter?.name && s.year === CommonUtils.extractYear(yearIter.date));
        yearIter.speakers = getSpeakers[0].lists;
        res.push(yearIter);
    }
    return {
        props: {
            year: params.year,
            data: res,
        },
    };
}

export async function getStaticPaths() {
    const paths = cities.map((city) => ({
        params: { year: CommonUtils.extractYear(city.date) },
    }));
    return {
        paths,
        fallback: false,
    };
}

const EditionSpeakers = (props) => {

    const year = props.year;
    const speakers = props.data.map(item => item.speakers)

    return <div>
        <Head>
            <title>AsyncAPI Conference {year}</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>


        <div
            id='speakers'
            className='pt-[50px] container relative flex flex-col items-center justify-center'
        >
            <div className='lg:py-20 w-[1130px] lg:w-full'>
                <div className='text-center'>
                    <Heading className='text-white'>Speakers</Heading>
                    <Paragraph className='mt-[20px] text-white'>Meet the amazing speakers of AACoT&apos;{year.toString().substring(2)}</Paragraph>
                </div>

                <div className='my-10'>
                    <div className='w-full mt-[30px] flex items-center justify-around flex-wrap'>
                            {speakers.flat().map((speaker, i) => {
                                return (
                                    <Speaker
                                        key={i}
                                        details={speaker}
                                        location={'India'}
                                        className=''
                                    />
                                );
                            })}
                    </div>

                </div>
            </div>
        </div>
    </div>
}

export default EditionSpeakers;