services:
  pretalx:
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: pretalx-mailpit
    restart: unless-stopped
    ports:
      - '127.0.0.1:8025:8025'
      - '127.0.0.1:1025:1025'
