/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import ReactGA from 'react-ga'
import TagManager from 'react-gtm-module'
import Navbar from '../components/Navbar/navbar';
import Header from '../components/Header/header';

export default function Home() {
	if (typeof window !== 'undefined') {
		TagManager.initialize({ gtmId: 'GTM-MCT2H5G' });
		ReactGA.initialize('UA-109278936-3');
		ReactGA.pageview(window.location.pathname + window.location.search);
	}
	return (
		<div>
			<Head>
				<title>AsyncAPI Conference</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<img src='/img/illustra.png' className='bg-01 bg-02' />
				<Navbar />
				<Header />
			</div>
		</div>
	);
}
