/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import { useEffect, useState } from 'react';
import Head from 'next/head';
import ReactGA from 'react-ga';
import TagManager from 'react-gtm-module';
import Header from '../components/Header/header';
import speakers from '../config/speakers.json';
import Sponsors from '../components/Sponsors/sponsors';
import About from '../components/About/about';
import { useMediaQuery } from 'react-responsive';

export default function Home() {
	const [city, setCity] = useState("");
	return (
		<div>
			<Head>
				<title>AsyncAPI Conference</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<img src='/img/illustra.png' className='color-effect' alt="background-illustration" />
			<Header />
			<div id='about' className='mt-20'>
				<About />
			</div>
			<div id='sponsors'>
				<Sponsors imgs={['/img/apidays.png']} />
			</div>
		</div>
	);
}
