import Head from "next/head";
import Heading from "../../components/Typography/heading";
import SearchBar from "../../components/Typography/search";
import FAQSection from "../../components/FAQ/faqSection";

const FeedBack = () => {
  return ( 
    <div>
      <Head>
        <title>FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-20 flex flex-col" >
        <div className="flex flex-col items-center justify-center">
          
          <FAQSection />
        </div>
        
      </div>
    </div>
    
   );
}
 
export default FeedBack;